### ISSUE TITLE
Consider adding  white-rabbit-rs to SeaORM showcase!

### ISSUE THREAD

**Issue by billy1624** [alices-wonderland/white-rabbit#2]
Hey @UkonnRa, feel free to submit a PR to showcase your project!
- https://github.com/SeaQL/sea-orm/issues/403

**Comment by UkonnRa** [comment]
Thanks for notifying me, I think this project is not ready yet. But SeaORM is actually the BEST ORM in the Rust world.

**Comment by billy1624** [comment]
Take your time! And thanks for the love and support :)
